import Head from 'next/head'
import Nav from "../components/Nav/Nav"
import Banner from "../components/Banner/Banner"
import Row from "../components/Row/Row"
import api from '../services/api'
import requests from '../utils/requests'

export default function Home({ movie, netflixOriginals, trendingNow, action, horror, comedy, documentries, romance }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Banner movie={movie} />
      <Row isLargeRow title="Netflix Originals" results={netflixOriginals} />
      <Row title="Trending Now" results={trendingNow} />
      <Row title="Action" results={action} />
      <Row title="Horror" results={horror} />
      <Row title="Comedy" results={comedy} />
      <Row title="Documentries" results={documentries} />
      <Row title="Romance" results={romance} />
    </>
  )
}

const fetchData = async (fetchUrl) => {
  const { data } = await api.base.get(fetchUrl)
  return data.results
}

export async function getServerSideProps() {
  const [netflixOriginals, trendingNow, action, horror, comedy, documentries, romance] = await Promise.all(
    [fetchData(requests.fetchNetflixOriginals),
      fetchData(requests.fetchTrendingNow),
      fetchData(requests.fetchActionMovies),
      fetchData(requests.fetchHorrorMovies),
      fetchData(requests.fetchComedyMovies),
      fetchData(requests.fetchDocumentries),
      fetchData(requests.fetchRomanceMovies),
    ])
  const movie = netflixOriginals[Math.floor(Math.random() * (netflixOriginals.length - 1))]

  return {
    props: {
        movie,
        netflixOriginals,
        trendingNow,
        action,
        horror,
        comedy,
        documentries,
        romance
    },
  }
}